owner: mcmod-info-mirror
repo: status

sites:
  - name: root
    url: https://mod.mcimirror.top
    expectedStatusCodes:
      - 200
    assignees:
      - z0z0r4
  - name: docs
    url: https://mod.mcimirror.top/docs
    expectedStatusCodes:
      - 200
    assignees:
      - z0z0r4
  - name: "Curseforge Search"
    url: https://mod.mcimirror.top/v1/curseforge/mods/search?gameId=432&pageSize=50
    expectedStatusCodes:
      - 200
    assignees:
      - z0z0r4
  - name: "Curseforge Mod"
    url: https://mod.mcimirror.top/v1/curseforge/mods/238222
    expectedStatusCodes:
      - 200
    assignees:
      - z0z0r4
  - name: "Curseforge Singel File"
    url: https://mod.mcimirror.top/v1/curseforge/mods/256717/files/2666198
    expectedStatusCodes:
      - 200
    assignees:
      - z0z0r4
  - name: "Curseforge Files"
    url: https://mod.mcimirror.top/v1/curseforge/mods/238222/files
    expectedStatusCodes:
      - 200
    assignees:
      - z0z0r4
  - name: "Curseforge Fingerprints"
    url: https://mod.mcimirror.top/v1/curseforge/fingerprints
    method: POST
    headers:
      - "Content-Type: application/json"
    body: '{"fingerprints": [1290884162]}'
    expectedStatusCodes:
      - 200
    assignees:
      - z0z0r4
  - name: "Modrinth Search"
    url: https://mod.mcimirror.top/v1/modrinth/search?offset=0&limit=10&index=relevance
    expectedStatusCodes:
      - 200
    assignees:
      - z0z0r4
  - name: "Modrinth Project"
    url: https://mod.mcimirror.top/v1/modrinth/project/sodium-extra
    expectedStatusCodes:
      - 200
    assignees:
      - z0z0r4
  - name: "Modrinth Versions"
    url: https://mod.mcimirror.top/v1/modrinth/project/sodium-extra/version
    expectedStatusCodes:
      - 200
    assignees:
      - z0z0r4
  - name: "Modrinth Single Version"
    url: https://mod.mcimirror.top/v1/modrinth/version/3JJvf9Kn
    expectedStatusCodes:
      - 200
    assignees:
      - z0z0r4
  - name: "Modrinth hash"
    url: https://mod.mcimirror.top/v1/modrinth/version_file/acac3670ee25cc10ed63136e5dd3b792acd13595
    expectedStatusCodes:
      - 200
    assignees:
      - z0z0r4

  - name: "Modrinth file cdn"
    url: https://mod.mcimirror.top/data/P7dR8mSH/versions/Y0cpssyN/fabric-api-0.100.6%2B1.21.jar
    expectedStatusCodes:
      - 307
      - 200
    assignees:
      - z0z0r4
  - name: "Curseforge file cdn"
    url: https://mod.mcimirror.top/files/5106/178/jei-1.19.2-forge-11.6.0.1019.jar
    expectedStatusCodes:
      - 307
      - 200
    assignees:
      - z0z0r4

workflowSchedule:
  uptime: "*/5 * * * *"

user-agent: mcmod-info-mirror/status

status-website:
  name: MCIM Uptime
  theme: light
  cname: status.mcimirror.top
