owner: mcmod-info-mirror
repo: status

sites:
  - name: API
    url: https://mcim.z0z0r4.top
    expectedStatusCodes:
      - 200
    assignees:
      - z0z0r4

workflowSchedule:
  uptime: "0 0 * * *"

skipDescriptionUpdate: true
skipTopicsUpdate: true
skipHomepageUpdate: true
