owner: mcmod-info-mirror
repo: status

sites:
  - name: root
    url: https://mcim.z0z0r4.top
    expectedStatusCodes:
      - 200
    assignees:
      - z0z0r4
  - name: docs
    url: https://mcim.z0z0r4.top/docs
    expectedStatusCodes:
      - 200
    assignees:
      - z0z0r4
  - name: "Curseforge Search"
    url: https://mcim.z0z0r4.top/v1/curseforge/mods/search?gameId=432&pageSize=50
    expectedStatusCodes:
      - 200
    assignees:
      - z0z0r4
  - name: "Curseforge Mod"
    url: https://mcim.z0z0r4.top/v1/curseforge/mods/238222
    expectedStatusCodes:
      - 200
    assignees:
      - z0z0r4
  - name: "Curseforge Files"
    url: https://mcim.z0z0r4.top/v1/curseforge/mods/238222/files
    expectedStatusCodes:
      - 200
    assignees:
      - z0z0r4
  - name: "Modrinth Search"
    url: https://mcim.z0z0r4.top/v1/modrinth/search?offset=0&limit=10&index=relevance
    expectedStatusCodes:
      - 200
    assignees:
      - z0z0r4
  - name: "Modrinth Project"
    url: https://mcim.z0z0r4.top/v1/modrinth/project/sodium-extra
    expectedStatusCodes:
      - 200
    assignees:
      - z0z0r4
  - name: "Modrinth Versions"
    url: https://mcim.z0z0r4.top/v1/modrinth/project/sodium-extra/version
    expectedStatusCodes:
      - 200
    assignees:
      - z0z0r4



workflowSchedule:
  uptime: "0 0 * * *"

user-agent: mcmod-info-mirror/status

status-website:
  baseUrl: /status
  name: MCIM Uptime
  theme: light
